version: "3"
services:
    # TODO:
    services:
# ...
    generator:
        build: ./generator
        environment:
            KAFKA_BROKER_URL: broker:9092
    
networks:
    default:
        external:
            name: kafka-network